const express = require('express');
const cors    = require('cors');
const morgan  = require('morgan');
const { Pool } = require('pg');
const { createProxyMiddleware } = require('http-proxy-middleware');
const app = express();
const PORT = process.env.PORT || 3001;
app.use(cors()); app.use(morgan('dev'));
const pool = new Pool({ host:process.env.DB_HOST||'localhost', port:process.env.DB_PORT||5432, database:process.env.DB_NAME||'medcore', user:process.env.DB_USER||'medcore', password:process.env.DB_PASSWORD||'medcore' });
app.use('/adt',           createProxyMiddleware({ target:'http://adt:3002',           changeOrigin:true, pathRewrite:{'^/adt':''}           }));
app.use('/scheduling',    createProxyMiddleware({ target:'http://scheduling:3003',    changeOrigin:true, pathRewrite:{'^/scheduling':''}    }));
app.use('/orders',        createProxyMiddleware({ target:'http://orders:3004',        changeOrigin:true, pathRewrite:{'^/orders':''}        }));
app.use('/results',       createProxyMiddleware({ target:'http://results:3005',       changeOrigin:true, pathRewrite:{'^/results':''}       }));
app.use('/documentation', createProxyMiddleware({ target:'http://documentation:3006', changeOrigin:true, pathRewrite:{'^/documentation':''} }));
app.use('/billing',       createProxyMiddleware({ target:'http://billing:3007',       changeOrigin:true, pathRewrite:{'^/billing':''}       }));
app.use('/mock-systems',  createProxyMiddleware({ target:'http://mock-proxy:3008',    changeOrigin:true, pathRewrite:{'^/mock-systems':''}   }));
app.use('/portal',        createProxyMiddleware({ target:'http://portal:3009',        changeOrigin:true, pathRewrite:{'^/portal':''}         }));
app.use(express.json());
app.get('/health', async (req,res)=>{ let db='ok'; try{await pool.query('SELECT 1');}catch{db='unavailable';} res.json({status:'ok',service:'medcore-gateway',version:'1.8.0',timestamp:new Date().toISOString(),dependencies:{database:db}}); });
app.use((req,res)=>res.status(404).json({error:'Not found'}));
app.listen(PORT,()=>console.log(`MedCore Gateway on :${PORT}`));
